services:
  postgres:
    image: postgres:latest
    container_name: data_modeling_lab_yh
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-yrkeshogskolan}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - data_modeling_lab_yh:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-yrkeshogskolan}" ]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  data_modeling_lab_yh:
    driver: local
